// Development.

// Get all contacts.
GET http://localhost:8080/contacts
###

// Get Tony Stark contact.
GET http://localhost:8080/contacts/644c2c05cd84282a3bfabf2a
###

// Get Thor Odinson contact.
GET http://localhost:8080/contacts/644c2d81cd84282a3bfcf640
###

// Get Bruce Banner contact.
GET http://localhost:8080/contacts/644c2deccd84282a3bfd93e0
###

// Production.

// Get all contacts.
GET https://contacts-project-cse341.onrender.com/contacts
###

// Get Tony Stark contact.
GET https://contacts-project-cse341.onrender.com/contacts/644c2c05cd84282a3bfabf2a
###

// Get Thor Odinson contact.
GET https://contacts-project-cse341.onrender.com/contacts/644c2d81cd84282a3bfcf640
###

// Get Bruce Banner contact.
GET https://contacts-project-cse341.onrender.com/contacts/644c2deccd84282a3bfd93e0